sudo: false
language: node_js
env: PHANTOMJS_BIN=./node_modules/.bin/phantomjs
node_js: 7
script:
  - npm run lint
  - npm run test
  - npm run build
after_success:
  - cat ./coverage/lcov.info | coveralls
